ALTER TABLE withdrawal_requests ADD COLUMN bank_account_id BIGINT NULL;
ALTER TABLE withdrawal_requests ADD COLUMN bank_code VARCHAR(20) NULL;
ALTER TABLE withdrawal_requests ADD COLUMN bank_name VARCHAR(100) NULL;
ALTER TABLE withdrawal_requests ADD COLUMN account_number VARCHAR(40) NULL;
ALTER TABLE withdrawal_requests ADD COLUMN account_holder VARCHAR(150) NULL;
ALTER TABLE withdrawal_requests ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE withdrawal_requests
    ADD CONSTRAINT fk_withdrawal_bank_account
    FOREIGN KEY (bank_account_id) REFERENCES bank_accounts(id) ON DELETE SET NULL;

CREATE TABLE withdrawal_action_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    withdrawal_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    old_status VARCHAR(20),
    new_status VARCHAR(20) NOT NULL,
    actor_id BIGINT NOT NULL,
    actor_name VARCHAR(150) NOT NULL,
    public_reason VARCHAR(500),
    internal_note VARCHAR(1000),
    transfer_reference VARCHAR(120),
    risk_level VARCHAR(10) NOT NULL,
    risk_findings TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_withdrawal_action_request FOREIGN KEY (withdrawal_id) REFERENCES withdrawal_requests(id),
    CONSTRAINT fk_withdrawal_action_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE TABLE withdrawal_export_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT NOT NULL,
    actor_name VARCHAR(150) NOT NULL,
    normalized_filters VARCHAR(2000) NOT NULL,
    operations_rows INTEGER NOT NULL,
    reconciliation_rows INTEGER NOT NULL,
    exported_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_withdrawal_export_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE INDEX idx_withdrawal_requested_status ON withdrawal_requests(status, requested_at DESC);
CREATE INDEX idx_withdrawal_destination_identity ON withdrawal_requests(bank_code, account_number);
CREATE INDEX idx_withdrawal_action_request_time ON withdrawal_action_history(withdrawal_id, created_at, id);
