CREATE TABLE bank_directory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    bin VARCHAR(12) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    qr_supported BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    directory_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO bank_directory (code, bin, display_name) VALUES
('VCB','970436','Vietcombank'), ('TCB','970407','Techcombank'),
('BIDV','970418','BIDV'), ('CTG','970415','VietinBank'),
('AGR','970405','Agribank'), ('ACB','970416','ACB'),
('MB','970422','MB Bank'), ('VPB','970432','VPBank'),
('STB','970403','Sacombank'), ('TPB','970423','TPBank'),
('HDB','970437','HDBank'), ('VIB','970441','VIB'),
('SHB','970443','SHB'), ('OCB','970448','OCB'),
('MSB','970426','MSB'), ('SEAB','970440','SeABank'),
('EIB','970431','Eximbank'), ('NAB','970428','Nam A Bank'),
('LPB','970449','LPBank'), ('SCB','970429','SCB'),
('BAB','970409','Bac A Bank'), ('ABB','970425','ABBANK'),
('PVCB','970412','PVcomBank'), ('VAB','970427','VietABank'),
('BVB','970438','BaoViet Bank'), ('NCB','970419','NCB'),
('KLB','970452','KienlongBank'), ('VBB','970433','VietBank'),
('SGICB','970400','SaigonBank'), ('GPB','970408','GPBank'),
('DOB','970406','DongA Bank'), ('OCEANBANK','970414','OceanBank'),
('VRB','970421','VRB'), ('WVN','970457','Woori'),
('SVB','970424','Shinhan Bank'), ('HLB','970442','Hong Leong'),
('SCVN','970410','Standard Chartered'), ('PBVN','970439','Public Bank'),
('IVB','970434','Indovina'), ('UOB','970458','UOB'),
('CIMB','422589','CIMB'), ('VCCB','970454','BVBank'),
('CAKE','546034','CAKE'), ('TIMO','963388','Timo');

ALTER TABLE bank_accounts ADD COLUMN bank_directory_id BIGINT NULL;
ALTER TABLE bank_accounts ADD COLUMN bank_bin VARCHAR(12) NULL;
ALTER TABLE withdrawal_requests ADD COLUMN bank_bin VARCHAR(12) NULL;

ALTER TABLE bank_accounts
    ADD CONSTRAINT fk_bank_account_directory
    FOREIGN KEY (bank_directory_id) REFERENCES bank_directory(id);

UPDATE bank_accounts account
SET bank_directory_id = directory.id,
    bank_bin = directory.bin,
    bank_name = directory.display_name
FROM bank_directory directory
WHERE UPPER(account.bank_code) = directory.code;

UPDATE withdrawal_requests withdrawal
SET bank_bin = directory.bin
FROM bank_directory directory
WHERE UPPER(withdrawal.bank_code) = directory.code;
