-- ===========================================================================
-- V7 — Organizer (Ban tổ chức) schema
-- Feature: B2B2C platform moderation. See docs/ba/2026-06-14-organizer-role-ba.md
-- and docs/db/2026-06-14-db-normalization-and-organizer-schema.md
-- Dialect: PostgreSQL. Forward-only; runs AFTER the prediction/enum migrations (V2–V6).
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- New tables
-- ---------------------------------------------------------------------------
create table organizations (
    id               bigint generated by default as identity not null,
    owner_user_id    bigint not null,
    approved_by      bigint,
    created_at       timestamp(6) not null,
    updated_at       timestamp(6),
    approved_at      timestamp(6),
    deleted_at       timestamp(6),
    status           varchar(30) not null
        check (status in ('PENDING','ACTIVE','SUSPENDED','REJECTED')),
    code             varchar(100) not null,
    name             varchar(200) not null,
    license_number   varchar(100),
    contact_email    varchar(150),
    contact_phone    varchar(30),
    logo_url         varchar(500),
    evidence_url     varchar(500),
    description      varchar(500),
    application_note text,
    rejection_reason varchar(255),
    primary key (id)
);

create table referee_contracts (
    id             bigint generated by default as identity not null,
    tournament_id  bigint not null,
    referee_id     bigint not null,
    invited_by     bigint not null,
    terminated_by  bigint,
    created_at     timestamp(6) not null,
    updated_at     timestamp(6),
    responded_at   timestamp(6),
    terminated_at  timestamp(6),
    status         varchar(30) not null
        check (status in ('PENDING','ACTIVE','DECLINED','TERMINATED')),
    agreement_url  varchar(500),
    reason         varchar(500),
    primary key (id)
);

-- ---------------------------------------------------------------------------
-- Unique constraints + foreign keys
-- ---------------------------------------------------------------------------
alter table organizations add constraint UK_organizations_code unique (code);
alter table organizations add constraint FK_org_owner       foreign key (owner_user_id) references users;
alter table organizations add constraint FK_org_approved_by foreign key (approved_by)   references users;

alter table referee_contracts add constraint UK_referee_contract unique (tournament_id, referee_id);
alter table referee_contracts add constraint FK_rc_tournament  foreign key (tournament_id) references tournaments;
alter table referee_contracts add constraint FK_rc_referee     foreign key (referee_id)    references users;
alter table referee_contracts add constraint FK_rc_invited_by  foreign key (invited_by)    references users;
alter table referee_contracts add constraint FK_rc_terminated_by foreign key (terminated_by) references users;

-- ---------------------------------------------------------------------------
-- Alter existing tables
-- ---------------------------------------------------------------------------
-- Tournament now belongs to an organization + carries the Cổng 2 approval audit.
-- organization_id stays NULLABLE for now (backfilled below); app enforces it on new tournaments.
alter table tournaments add column organization_id  bigint;
alter table tournaments add column approved_by       bigint;
alter table tournaments add column approved_at       timestamp(6);
alter table tournaments add column rejection_reason  varchar(255);
alter table tournaments add constraint FK_tournament_org         foreign key (organization_id) references organizations;
alter table tournaments add constraint FK_tournament_approved_by foreign key (approved_by)      references users;

-- Allow account suspension (BR-10/BR-13). NOT VALID mirrors T-SQL "WITH NOCHECK":
-- existing rows are not validated, only new writes. Values MUST match the UserStatus enum.
alter table users add constraint CK_users_status
    check (status in ('ACTIVE','PENDING_EMAIL_VERIFY','SUSPENDED','INACTIVE','BANNED')) not valid;

-- ---------------------------------------------------------------------------
-- Reference seed: ORGANIZER role
-- ---------------------------------------------------------------------------
insert into roles (name, description)
select 'ORGANIZER', 'Organizer'
where not exists (select 1 from roles r where r.name = 'ORGANIZER');

-- ---------------------------------------------------------------------------
-- Backfill: attach legacy tournaments to a default "Platform Organization".
-- Idempotent + safe across environments (no-op if there is no ADMIN user).
-- T-SQL EXEC/DECLARE/SELECT TOP 1/SCOPE_IDENTITY -> PL/pgSQL DO block with
-- SELECT ... LIMIT 1 and INSERT ... RETURNING id INTO.
-- ---------------------------------------------------------------------------
do $$
declare
    admin_id bigint;
    org_id   bigint;
begin
    select u.id into admin_id
    from users u
    join user_roles ur on ur.user_id = u.id
    join roles r on r.id = ur.role_id
    where r.name = 'ADMIN' and ur.status = 'ACTIVE'
    order by u.id
    limit 1;

    if admin_id is not null and exists (select 1 from tournaments where organization_id is null) then
        select id into org_id from organizations where code = 'PLATFORM_DEFAULT' limit 1;
        if org_id is null then
            insert into organizations (owner_user_id, approved_by, created_at, approved_at, status, code, name, description)
            values (admin_id, admin_id, now(), now(), 'ACTIVE', 'PLATFORM_DEFAULT',
                    'Platform Organization', 'Auto-created for tournaments that predate the organizer feature.')
            returning id into org_id;
        end if;
        update tournaments set organization_id = org_id where organization_id is null;
    end if;
end $$;
