package com.example.horseracingtournamentsystem.point.entity;

public enum PointSettingKey {
    FIRST_LOGIN_BONUS,
    BLOG_REWARD_POINTS,
    DAILY_BLOG_REWARD_LIMIT,
    PREDICTION_WINNER_ENTRY_COST,
    PREDICTION_TOP3_ENTRY_COST,
    PREDICTION_WINNER_REWARD,
    PREDICTION_TOP3_EXACT_REWARD,
    PREDICTION_TOP3_ANY_ORDER_REWARD;
}
